[package]
name = "tau-regge"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tau-math.workspace = true
nalgebra.workspace = true
rand = "0.8"

[dev-dependencies]
approx = "0.5"
