[package]
name = "tau-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "WASM bindings for tau physics engine"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
tau-math.workspace = true
tau-model.workspace = true
tau-rigid.workspace = true
tau-diff.workspace = true
