[package]
name = "tau-compile"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nalgebra.workspace = true
tau-math.workspace = true
naga = "23.0"
wgpu = "23.0"

[dev-dependencies]
approx = "0.5"
