[package]
name = "tau-md"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nalgebra.workspace = true
tau-math.workspace = true

[dev-dependencies]
approx = "0.5"
