[package]
name = "phyz-contact"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nalgebra.workspace = true
phyz-math.workspace = true
phyz-model.workspace = true
phyz-collision.workspace = true
