[package]
name = "phyz-coupling"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
phyz-math = { workspace = true }
nalgebra.workspace = true

[dev-dependencies]
approx = "0.5"
