[package]
name = "tau-coupling"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tau-math = { workspace = true }
nalgebra.workspace = true

[dev-dependencies]
approx = "0.5"
